# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
rand_tensor = torch.rand(size=(7, 7))
rand_tensor

tensor([[0.1529, 0.2214, 0.2073, 0.9315, 0.6969, 0.9369, 0.5349],
        [0.0863, 0.7706, 0.4068, 0.7027, 0.3208, 0.8207, 0.3433],
        [0.0361, 0.5645, 0.4337, 0.7169, 0.7348, 0.1879, 0.1666],
        [0.8712, 0.3919, 0.8871, 0.2814, 0.8242, 0.5113, 0.0498],
        [0.1618, 0.7208, 0.8945, 0.8102, 0.8522, 0.2448, 0.6211],
        [0.5984, 0.8460, 0.9169, 0.4428, 0.7557, 0.9960, 0.3853],
        [0.0093, 0.1695, 0.8778, 0.5237, 0.8440, 0.0597, 0.2069]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
another_tensor = torch.rand(size=(1, 7))
# Perform matrix multiplication
result = torch.matmul(rand_tensor, another_tensor.T)
print(result)

tensor([[1.5254],
        [1.1129],
        [0.9793],
        [1.3416],
        [1.3280],
        [1.7143],
        [0.9555]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
tensor_A = torch.rand(7, 7)
tensor_B = torch.rand(1, 7)

# Matrix multiply tensors
result_tensor = torch.matmul(tensor_A, tensor_B.T)
result_tensor, result_tensor.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
RANDOM_SEED = 1234
torch.mps.manual_seed(RANDOM_SEED)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [9]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
    device = 'cuda'
elif torch.backends.mps.is_available():
    device = 'mps'
else:
    device = 'cpu'

# Create two random tensors on GPU
tensor_C = torch.rand(2, 3)
tensor_D = torch.rand(2, 3)
tensor_C = tensor_C.to(device)
tensor_D = tensor_D.to(device)
print(f'Device: {device}')
tensor_C, tensor_D

Device: mps


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='mps:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [11]:
# Perform matmul on tensor_C and tensor_D
result = torch.matmul(tensor_C, tensor_D.T)
result, result.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='mps:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [19]:
# Find max
max_val = result.max()
print(f'max val: {max_val}')

# Find min
min_val = result.min()
print(f'min val: {min_val}')

max val: 0.5617256760597229
min val: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [21]:
# Find arg max
print(f'Index of max: {torch.argmax(result)}')

# Find arg min
print(f'Index of min: {torch.argmin(result)}')

Index of max: 3
Index of min: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [24]:
# Set seed
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)

# Create random tensor
tensor_E = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_F = torch.squeeze(tensor_E)

# Print out tensors and their shapes
print(tensor_E, tensor_E.shape)
print(tensor_F, tensor_F.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
