## 00. PyTorch Fundamentals
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have any question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
print("Hello I'm excited to learn Pytorch!")

Hello I'm excited to learn Pytorch!


### Importing PyTorch

In [2]:
import torch
torch.__version__

'2.2.2'

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Creating tensors

In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.shape

torch.Size([])

In [7]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7, 7])
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
# Check number of dimensions
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [15]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

In [16]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.1672, 0.8730, 0.1963, 0.6251],
         [0.6171, 0.3619, 0.0057, 0.0524],
         [0.9487, 0.0786, 0.6156, 0.5976]]),
 torch.float32)

In [17]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating a range and tensors like

In [19]:
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future
zero_to_ten_deprecated

/var/folders/dl/zlcf_v7n60z8pgq6gpngkskh0000gn/T/ipykernel_7158/722120435.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
# Default data type for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [23]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor.shape, float_16_tensor.dtype, float_16_tensor.device

(torch.Size([3]), torch.float16, device(type='cpu'))

### Getting information from tensors

* `shape` - what shape is the tensor? (some operations require specific shape rules)
* `dtype` - what datatype are the elements within the tensor stored in?
* `device` - what device is the tensor stored on? (usually GPU or CPU)

In [24]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f'Shape of tensor: {some_tensor.shape}')
print (f'Data type of tensor: {some_tensor.dtype}')
print(f'Device tensor is stored on: {some_tensor.device}')

tensor([[0.4413, 0.8479, 0.9294, 0.8502],
        [0.9162, 0.8913, 0.0630, 0.1027],
        [0.4638, 0.4428, 0.7950, 0.2472]])
Shape of tensor: torch.Size([3, 4])
Data type of tensor: torch.float32
Device tensor is stored on: cpu


### Manipulating tensors (tensor operations)

In [25]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [26]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [27]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [28]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [29]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [30]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [31]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

In [32]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(f'{tensor} * {tensor} = ')
print(tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3]) = 
tensor([1, 4, 9])


In [33]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error)

torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [34]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [35]:
tensor_A

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [36]:
tensor_A.shape

torch.Size([3, 2])

In [37]:
# input node = 2 node
# output node = 6 node

torch.manual_seed(42)

Linear = torch.nn.Linear(in_features=2,
                         out_features=6)

x = tensor_A
y = Linear(x)

print(f'Input shape: {x.shape}')
print(f'Output shape: {y.shape}')
print(y)

Input shape: torch.Size([3, 2])
Output shape: torch.Size([3, 6])
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)


In [39]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
print(f'Minimum: {x.min()}')
print(f'Maximum: {x.max()}')
print(f'Mena: {x.type(torch.float).mean()}')
print(f'Sum: {x.sum()}')

Minimum: 0
Maximum: 90
Mena: 45.0
Sum: 450


In [48]:
print(f'Minimum: {torch.min(x)}')
print(f'Maximum: {torch.max(x)}')
print(f'Mena: {torch.mean(x.type(torch.float))}')
print(f'Sum: {torch.sum(x)}')

Minimum: 0
Maximum: 90
Mena: 45.0
Sum: 450


In [50]:
# Create a tensor
tensor = torch.arange(0, 100, 10)
print(f'tensor = {tensor}')

# Return index of max and min values
print(f'Index of min value: {torch.argmin(tensor)}')
print(f'Index of max value: {torch.argmax(tensor)}')

tensor = tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Index of min value: 0
Index of max value: 9


In [57]:
# Create a tensor and check it's data type
tensor = torch.arange(0., 100., 10.)
tensor, tensor.dtype

(tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]), torch.float32)

In [55]:
# Create a float16 tensor
float_16_tensor = tensor.type(torch.float16)
float_16_tensor

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [58]:
# Create a int8 tensor
int_8_tensor = tensor.type(torch.int8)
int_8_tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [59]:
# Create a tensor
x = torch.arange(1., 8.)
x

tensor([1., 2., 3., 4., 5., 6., 7.])

In [60]:
x.shape

torch.Size([7])

In [61]:
# Reshape
x_reshaped = x.reshape(1, 7)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [62]:
x_reshaped.shape

torch.Size([1, 7])

In [63]:
# Change view (keeps same data as original but changes view)
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [65]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [66]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7.]])

In [68]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [69]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [71]:
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# Remove extra dimension from x_shaped
print('Remove extra dimension from x_shaped')
x_squeezed = x_reshaped.squeeze()
print(f'New tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])
Remove extra dimension from x_shaped
New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [74]:
# Create a tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
# shifts axis 0->1, 1->2, 2->0
x_permuted = x_original.permute(2, 0, 1)

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}')

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [79]:
# Indexing

# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
print(f'x =\n {x}')
print(f'shape : {x.shape}')

x =
 tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
shape : torch.Size([1, 3, 3])


In [86]:
print(f'First bracket:\n {x[0]} \n')
print(f'Second bracket:\n {x[0][0]} \n')
print(f'Third bracket:\n {x[0][0][0]}')

First bracket:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) 

Second bracket:
 tensor([1, 2, 3]) 

Third bracket:
 1


In [87]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [89]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [90]:
# change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [91]:
# tensor to Numpy array
tensor = torch.ones(7)
array = tensor.numpy()
tensor, array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))